name: hola mundo

on:
    push:
        branches:
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hola mundo!
              run: echo "hola mundo!"