name: hola-mundo

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World!
        run: echo "Hello World"
=======
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hola mundo!
>>>>>>> b64cbc04d414c9081b90c8a994fb86041d6eb0ed
              run: echo "hola mundo!"
>>>>>>> b31493a5ddf87c17c17a79187b530e9b735a504b
